[package]
name = "scavenge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stack-tokens = "0.1.0"
generativity = "1.0.1"
