[package]
name = "scavenge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generativity = "1.0.1"
roaring = "0.10.1"
